#!/usr/bin/env python3
import argparse
import logging as l
from history import sync_price_history
from update import update_dumps
from schema import get_db


if __name__ == "__main__":
  l.basicConfig(level=l.INFO)

  action_funcs = {
      'update': update_dumps,
      'history': sync_price_history,
      'migrate': lambda args: get_db(migrate=True),
      }

  parser = argparse.ArgumentParser(description='apartment hunter')
  parser.add_argument('action', choices=action_funcs.keys())
  parser.add_argument('--local',
      action="store_true", help='use local sheets data')
  parser.add_argument('--dry-run',
      action="store_true", help='dont make changes')
  args = parser.parse_args()
  action_funcs[args.action](args)
